dist: trusty
sudo: required
language: cpp
compiler:
    gcc
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y pkg-config libgtkmm-3.0-dev
script:
    ./configure --disable-grop & make 

notifications:
    email:
        on_success: never
        on_failure: always    
