dist: trusty
sudo: required
language: cpp
compiler:
    gcc
before_install:
    sudo apt-get update
    sudo apt-get intall pkg-config libgtkmm-3.0-dev
script:
    ./configure --disable-grop & make & make test
